//
//  LanguageConstant.swift
//  Shopper
//
//  Created by Theappfathers on 18/01/21.
//  Copyright © 2021 Theappfathers. All rights reserved.
//

import Foundation

struct Language{
    
    static let login            = "Login"
    
    static let MyOrder          = "MyOrder"
    static let MyWishlist       = "MyWishlist"
    static let MyAddress        = "MyAddress"
    static let ChangePassword   = "ChangePassword"
    static let ChangeLanguage   = "ChangeLanguage"
    static let AboutUS          = "AboutUS"
    static let ContactUs        = "ContactUs"
    static let MyNotification   = "MyNotification"
    static let TermsCondition   = "TermsCondition"
    static let Logout           = "Logout"

    static let ExploreMallText  = "ExploreMallText"
    static let PromoText        = "PromoText"
    static let CategoriesText   = "CategoriesText"
    static let ShoppersText     = "ShoppersText"
    static let SearchProduct    = "SearchProduct"

    
    static let MyProfile        = "MyProfile"
    static let Name             = "Name"
    static let Email            = "Email"
    static let Mobile           = "Mobile"
    static let Update           = "Update"

    static let MyNotifications  = "MyNotifications"

    static let CurrentPassword  = "CurrentPassword"
    static let NewPassword  = "NewPassword"
    static let ConﬁrmPassword  = "ConﬁrmPassword"
    static let ResetPassword  = "ResetPassword"

    static let Chat  = "Chat"
    static let CreateOffer      = "CreateOffer"
    static let AddOfferPrice      = "AddOfferPrice"
    static let Products             = "Products"
 
    static let AddProduct            = "AddProduct"
    static let ProductName           = "ProductName"
    static let SelectStore           = "SelectStore"
    static let StoreDescription      = "StoreDescription"
    static let ProductPrice          = "ProductPrice"
    static let ProductSellPrice      = "ProductSellPrice"
    static let ProductTags           = "ProductTags"
    static let SelectProductPhoto    = "SelectProductPhoto"
    static let Store                 = "Store"
    static let AddStore              = "AddStore"
    static let StoreName             = "StoreName"
    static let Categories            = "Categories"
    static let SelectStorePhotos     = "SelectStorePhotos"

    static let TotalChats            = "TotalChats"
    static let TotalStores           = "TotalStores"
    static let TotalProducts         = "TotalProducts"
    static let TotalAmounts          = "TotalAmounts"
    
    static let AddAddress            = "AddAddress"
    
    
    static let AddressLine1         =   "AddressLine1"
    static let AddressLine2         =   "AddressLine2"
    static let City                 =   "City"
    static let State                =   "State"
    static let Country              =   "Country"
    static let ZipCode              =   "ZipCode"
    static let HomeWorkOther        =   "HomeWorkOther"
    static let ADD                  =   "ADD"
    static let OrderDetails         = "OrderDetails"
    static let Addons               = "Addons"
    static let TotalPrice           = "TotalPrice"
    static let CheckOut             = "CheckOut"
    static let SearchProducts       = "SearchProducts"
    static let NoDataFound          = "NoDataFound"
    static let Checkout             = "Checkout"
    static let ShippingTo           = "ShippingTo"
    static let ChangeOrAddAddress   = "ChangeOrAddAddress"
    static let Items                = "Items"
    static let PaymentMethod        = "PaymentMethod"
    static let Online               = "Online"
    static let CashOnDelivery       = "CashOnDelivery"
    static let PriceDetails         = "PriceDetails"
    static let SubTotal             = "SubTotal"
    static let DeliveryCharge       = "DeliveryCharge"
    static let ShopperCharge        = "ShopperCharge"
    static let TotalAmount          = "TotalAmount"
    static let PlaceOrder           = "PlaceOrder"
    static let Category             = "Category"
    static let BuyNow               = "BuyNow"
    static let ChatWithSeller       = "ChatWithSeller"
    static let MRP                  = "Price"
    static let OK                   = "OK"
    static let Cancel               = "Cancel"
    static let Quantity             = "Quantity"
    static let SelectOptionforUploadImage = "SelectOptionforUploadImage"
    static let Camera                = "Camera"
    static let Photos                = "Photos"
    static let No                    = "No"
    static let YesDeleteIt           = "YesDeleteIt"
    static let AreYouSureYouWantToRemove    = "AreYouSureYouWantToRemove"
    static let OrderID              = "OrderID"
    static let DeliveredOn          = "DeliveredOn"
    static let Removeitem           = "Removeitem"
    static let AddNewAddress        = "AddNewAddress"
    static let DeleverHere          = "DeleverHere"
    static let UpdateAddress        = "UpdateAddress"
    static let Are_you_sureYouLogout = "Are_you_sureYouLogout"
    static let Select_one_fromAssistances = "Select_one_fromAssistances"
    static let Ratings              = "Ratings"
    static let NONE                 = "NONE"
    static let PersonalShoppers     = "PersonalShoppers"
    static let ViewAll              = "ViewAll"
    
    static let ToDo                 =  "ToDo"
    static let CHOOSE_ASSISTANT     =  "CHOOSE_ASSISTANT"
    static let FAVORITE_MALL        =  "FAVORITE_MALL"
    static let GOT_YOU_COVERED      =  "GOT_YOU_COVERED"
    static let CHOOSE_AN            =  "CHOOSE_AN"
    static let START_BY             =  "START_BY"
    static let Signup               =  "Signup"
    static let SignUp               =  "SignUp"

    static let GUEST                =  "GUEST"
    static let Password             =  "Password"
    static let ForgotPassword       = "ForgotPassword"
    static let SignupNow            = "SignupNow"
    static let DontHaveAccess       = "DontHaveAccess"
    static let  OTP                 = "OTP"
    static let  VERIFY_YOUR_NUMBER  = "VERIFY_YOUR_NUMBER"
    static let  Please_enter_the_OTP_sent_to = "Please_enter_the_OTP_sent_to"
    static let  Resend_OTP          = "Resend_OTP"
    static let  Confirm             = "Confirm"

    static let Username             = "Username"
    static let Code                 = "Code"
    static let ConfirnPassword      = "ConfirnPassword"
    static let BackToLogin          = "BackToLogin"
    static let AgreeTermsCondition  = "AgreeTermsCondition"
    static let Status               = "Status"
    static let Support              = "Support"
    static let LetsOrder            = "LetsOrder"
    static let Submit               = "Submit"
    static let If_You_Have          = "If_You_Have"
    static let Title                = "Title"
    static let SuccessfullySend     = "SuccessfullySend"
    static let OurTeam              = "OurTeam"
    static let there_is_no_item     = "there_is_no_item"
    static let Reviews              = "Reviews"
    static let Message              = "Message"
    static let it_will_based_on_language = "it_will_based_on_language"
    static let Store_name_in_arabic = "Store_name_in_arabic"
    static let ProductNameArabic = "ProductNameArabic"
    static let Product_Description = "Product Description"
    static let Product_Description_in_Arabic = "Product Description in Arabic"
    
    static let DeliveryAddress      = "DeliveryAddress"
    static let OrderInformation     = "OrderInformation"
    static let PaymentType          = "PaymentType"
    static let DeliveredBy          = "DeliveredBy"
    static let OrderStatus          = "OrderStatus"
    static let OrderOn              = "OrderOn"
    static let DeliveryCharges      = "DeliveryCharges"
    static let ShopperCharges       = "ShopperCharges"
    static let start_Order          = "start_Order"
    
}


